import type { Shoe } from "./types";

/**
 * 러닝화 DB v3 — 2026년 현행 판매 모델 기준
 *
 * priceKrw: 2026년 6월 기준 한국 공식가
 * primaryBodyTypes: 각 신발이 최적인 체형 (1~3개)
 *
 * 체형 분류:
 *   small_light  키≤163 / ≤55kg
 *   small_mid    키≤163 / 56-75kg
 *   small_heavy  키≤163 / 76kg+
 *   mid_light    키164-177 / ≤60kg
 *   mid_mid      키164-177 / 61-80kg
 *   mid_heavy    키164-177 / 81kg+
 *   tall_mid     키178+ / ≤85kg
 *   tall_heavy   키178+ / 86kg+
 */

export const SHOES: Shoe[] = [
  {
    id: "saucony-kinvara-16",
    brand: "Saucony",
    model: "Kinvara 16",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40882/saucony-kinvara-16-24182303-main.jpg",
    colorways: ["화이트/비사이드", "네온 옐로우"],
    widthOptions: ["D"],
    heelDropMm: 5,
    stackHeightMm: 28,
    weightGramsM9: 207,
    priceUsd: 140,
    priceKrw: 185000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "플릿러너 — 한국 공인딜러", url: "https://www.fleetrunner.co.kr/search?keyword=Kinvara%2016", isOfficial: false },
      { label: "29CM 검색", url: "https://www.29cm.co.kr/search?keyword=Kinvara%2016", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%82%AC%EC%BD%94%EB%8B%88%20%ED%82%A4%EB%82%98%EB%9D%BC%2016", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Saucony%20Kinvara%2016", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Saucony%20Kinvara%2016", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/saucony-kinvara-16",
    cushioning: 2,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [40, 62],
    heightRangeCm: [145, 170],
    primaryBodyTypes: ["small_light", "mid_light"],
    uses: ["daily", "tempo"],
    blurb: "207g 초경량 + 드롭 5mm. 소형·경량 러너의 미드풋 데일리 최적.",
    scienceBasis: "드롭 5mm — 소형 러너의 짧은 보폭에서 미드풋 착지 자연 유도 (Heiderscheit 2011).",
    youtubeReviews: [
      { label: "Kinvara 16 리뷰", url: "https://www.youtube.com/results?search_query=saucony+kinvara+16" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=사코니+키나라+16+리뷰" },
      { label: "비교 영상", url: "https://www.youtube.com/results?search_query=kinvara+16+review" },
    ],
  },
  {
    id: "nb-fuelcell-rebel-v4",
    brand: "New Balance",
    model: "FuelCell Rebel v4",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40311/new-balance-fuel-cell-rebel-v-4-21446877-720.jpg",
    colorways: ["일렉트릭 블루", "네온 옐로우"],
    widthOptions: ["D", "2E"],
    heelDropMm: 6,
    stackHeightMm: 30,
    weightGramsM9: 212,
    priceUsd: 140,
    priceKrw: 179000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "뉴발란스 공식몰", url: "https://www.newbalance.co.kr/ko/search?q=FuelCell+Rebel", isOfficial: true },
      { label: "무신사 — New Balance", url: "https://www.musinsa.com/brand/newbalance", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%89%B4%EB%B0%9C%EB%9E%80%EC%8A%A4%20%ED%93%A8%EC%96%BC%EC%85%80%20%EB%A6%AC%EB%B2%A8", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=New%20Balance%20FuelCell%20Rebel%20v4", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=New%20Balance%20FuelCell%20Rebel%20v4", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/new-balance-fuelcell-rebel-v4",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 78],
    heightRangeCm: [148, 180],
    primaryBodyTypes: ["small_light", "small_mid", "mid_light"],
    uses: ["tempo", "daily", "racing"],
    blurb: "212g 경량 템포화. 소형·경량 러너 하프마라톤 최적.",
    scienceBasis: "FuelCell 폼 낮은 드롭 — 경량 러너 미드풋 착지 에너지 반환 효율 높음.",
    youtubeReviews: [
      { label: "FuelCell Rebel 리뷰", url: "https://www.youtube.com/results?search_query=FuelCell+Rebel+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=뉴발란스+퓨얼셀+리벨+리뷰" },
      { label: "비교 영상", url: "https://www.youtube.com/results?search_query=FuelCell+Rebel+v4+vs+comparison" },
    ],
  },
  {
    id: "adidas-adizero-adios-pro-4",
    brand: "Adidas",
    model: "Adizero Adios Pro 4",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40584/adidas-adizero-adios-pro-4-22483965-720.jpg",
    colorways: ["클라우드 화이트/코어 블랙"],
    widthOptions: ["D"],
    heelDropMm: 6,
    stackHeightMm: 40,
    weightGramsM9: 200,
    priceUsd: 260,
    priceKrw: 360000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아디다스 공식몰", url: "https://www.adidas.co.kr/search?q=Adizero+Adios+Pro", isOfficial: true },
      { label: "무신사 — Adidas", url: "https://www.musinsa.com/brand/adidas", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EB%94%94%EB%8B%A4%EC%8A%A4%20%EC%95%84%EB%94%94%EC%A0%9C%EB%A1%9C%20%EC%95%84%EB%94%94%EC%98%A4%EC%8A%A4%20%ED%94%84%EB%A1%9C%204", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Adidas%20Adizero%20Adios%20Pro%204", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Adidas%20Adizero%20Adios%20Pro%204", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/adidas-adizero-adios-pro-4",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [40, 72],
    heightRangeCm: [148, 178],
    primaryBodyTypes: ["small_light", "mid_light"],
    uses: ["racing"],
    blurb: "200g 카본 레이싱화. 소형·경량 러너 풀마라톤 기록 단축.",
    scienceBasis: "EnergyRods 2.0 카본 — 족저굴곡 강성 극대화로 추진 효율 6-8% 향상 (Hoogkamer 2018 응용).",
    youtubeReviews: [
      { label: "Adios Pro 4 리뷰", url: "https://www.youtube.com/results?search_query=adizero+adios+pro+4+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아디다스+아디오스+프로4+리뷰" },
      { label: "레이싱화 비교", url: "https://www.youtube.com/results?search_query=adios+pro+4+vs+vaporfly+comparison" },
    ],
  },
  {
    id: "hoka-clifton-10",
    brand: "Hoka",
    model: "Clifton 10",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40691/hoka-clifton-10-22918659-720.jpg",
    colorways: ["스카이 블루", "미스트/화이트"],
    widthOptions: ["D", "2E", "4E"],
    heelDropMm: 8,
    stackHeightMm: 43,
    weightGramsM9: 278,
    priceUsd: 145,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "호카 공식몰 — 클리프톤", url: "https://www.hoka.com/ko-kr/running/road/clifton/", isOfficial: true },
      { label: "무신사 — Hoka", url: "https://www.musinsa.com/brand/hoka", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%ED%98%B8%EC%B9%B4%20%ED%81%B4%EB%A6%AC%ED%94%84%ED%86%A4%2010", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Hoka%20Clifton%2010", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Hoka%20Clifton%2010", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/hoka-clifton-10",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [50, 85],
    heightRangeCm: [148, 178],
    primaryBodyTypes: ["small_mid", "small_light"],
    uses: ["daily", "long"],
    blurb: "드롭 8mm + 스택 43mm. 소형·중량 러너 맥시멀 쿠션 데일리.",
    scienceBasis: "높은 스택 + 드롭 8mm — 소형 러너의 착지 충격 분산과 힐스트라이커 수용 동시 달성.",
    youtubeReviews: [
      { label: "Hoka Clifton 10 리뷰", url: "https://www.youtube.com/results?search_query=hoka+clifton+10+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=호카+클리프톤+10+리뷰" },
      { label: "Clifton 10 vs 9 비교", url: "https://www.youtube.com/results?search_query=clifton+10+vs+clifton+9" },
    ],
  },
  {
    id: "asics-gt-2000-14",
    brand: "Asics",
    model: "GT-2000 14",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40930/asics-gt-2000-14-23520459-main.jpg",
    colorways: ["딥 오션", "블랙/카본"],
    widthOptions: ["D", "2E", "4E"],
    heelDropMm: 9,
    stackHeightMm: 37,
    weightGramsM9: 273,
    priceUsd: 130,
    priceKrw: 169000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰 — GT-2000 14", url: "https://www.asics.co.kr/goods/search?search_text=GT-2000", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EC%8B%9D%EC%8A%A4%20GT-2000%2014", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20GT-2000%2014", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20GT-2000%2014", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-gt-2000-14",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [50, 88],
    heightRangeCm: [148, 178],
    primaryBodyTypes: ["small_mid", "mid_mid"],
    uses: ["daily"],
    blurb: "평발·보통 발볼 소형 러너 가성비 안정화. 드롭 9mm 힐스트라이커 친화.",
    scienceBasis: "LYTE TRUSS 경량 안정화 — 과회내 제어하면서 소형 러너 체중에 적합한 쿠션 밀도.",
    youtubeReviews: [
      { label: "GT-2000 14 리뷰", url: "https://www.youtube.com/results?search_query=asics+gt+2000+14+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+GT2000+14+리뷰" },
      { label: "안정화 비교", url: "https://www.youtube.com/results?search_query=gt+2000+14+vs+kayano+comparison" },
    ],
  },
  {
    id: "hoka-bondi-9",
    brand: "Hoka",
    model: "Bondi 9",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40639/hoka-bondi-9-22560581-720.jpg",
    colorways: ["화이트/화이트", "블랙/블랙"],
    widthOptions: ["D", "2E"],
    heelDropMm: 5,
    stackHeightMm: 40,
    weightGramsM9: 298,
    priceUsd: 175,
    priceKrw: 239000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "호카 공식몰 — 본디", url: "https://www.hoka.com/ko-kr/running/road/bondi/", isOfficial: true },
      { label: "무신사 — Hoka", url: "https://www.musinsa.com/brand/hoka", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%ED%98%B8%EC%B9%B4%20%EB%B3%B8%EB%94%94", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Hoka%20Bondi%209", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Hoka%20Bondi%209", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/hoka-bondi-9",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [65, 120],
    heightRangeCm: [148, 178],
    primaryBodyTypes: ["small_heavy", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "스택 40mm 맥시멀 쿠션. 소형·고체중 러너 관절 보호 최우선.",
    scienceBasis: "맥시멀 쿠션 — 고체중 러너(65kg+) 착지 충격 최대 흡수, van Gent 2007 부상 위험 감소.",
    youtubeReviews: [
      { label: "Hoka Bondi 9 리뷰", url: "https://www.youtube.com/results?search_query=hoka+bondi+9+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=호카+본디9+리뷰" },
      { label: "Bondi vs Clifton 비교", url: "https://www.youtube.com/results?search_query=hoka+bondi+9+vs+clifton+comparison" },
    ],
  },
  {
    id: "asics-gel-kayano-32",
    brand: "Asics",
    model: "Gel-Kayano 32",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40809/asics-gel-kayano-32-23240127-720.jpg",
    colorways: ["블랙/화이트", "화이트/오렌지글로우"],
    widthOptions: ["D", "2E", "4E"],
    heelDropMm: 8,
    stackHeightMm: 40,
    weightGramsM9: 298,
    priceUsd: 160,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰 — 젤카야노 32", url: "https://www.asics.co.kr/goods/search?search_text=Gel-Kayano", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EC%8B%9D%EC%8A%A4%20%EC%A0%A4%20%EC%B9%B4%EC%95%BC%EB%85%B8%2032", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Gel-Kayano%2032", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Gel-Kayano%2032", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-gel-kayano-32",
    cushioning: 4,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [60, 100],
    heightRangeCm: [148, 178],
    primaryBodyTypes: ["small_heavy", "mid_heavy"],
    uses: ["daily"],
    blurb: "드롭 8mm 안정화. 소형·고체중 평발 러너 과회내 제어.",
    scienceBasis: "4D Guidance System — 발 내측 지지로 과회내 보정, Richards 2009 족저 압력 분산.",
    youtubeReviews: [
      { label: "Kayano 32 리뷰", url: "https://www.youtube.com/results?search_query=asics+gel+kayano+32+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+카야노+32+리뷰" },
      { label: "카야노 vs GT-2000 비교", url: "https://www.youtube.com/results?search_query=kayano+32+vs+gt+2000+comparison" },
    ],
  },
  {
    id: "saucony-endorphin-speed-5",
    brand: "Saucony",
    model: "Endorphin Speed 5",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40830/saucony-endorphin-speed-5-23261039-720.jpg",
    colorways: ["블루/화이트", "블랙/골드"],
    widthOptions: ["D"],
    heelDropMm: 8,
    stackHeightMm: 37,
    weightGramsM9: 220,
    priceUsd: 175,
    priceKrw: 229000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "플릿러너 — 한국 공인딜러", url: "https://www.fleetrunner.co.kr/search?keyword=Endorphin%20Speed%205", isOfficial: false },
      { label: "29CM 검색", url: "https://www.29cm.co.kr/search?keyword=Endorphin%20Speed%205", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%82%AC%EC%BD%94%EB%8B%88%20%EC%97%94%EB%8F%84%EB%A5%B4%ED%95%80%20%EC%8A%A4%ED%94%BC%EB%93%9C%205", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Saucony%20Endorphin%20Speed%205", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Saucony%20Endorphin%20Speed%205", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/saucony-endorphin-speed-5",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 78],
    heightRangeCm: [158, 180],
    primaryBodyTypes: ["mid_light", "small_light"],
    uses: ["tempo", "racing", "daily"],
    blurb: "경량 템포화 + PWRRUN PB 폼. 중형·경량 러너 하프·풀 기록 단축.",
    scienceBasis: "PWRRUN PB 폼 — 경량 러너 미드풋 착지 에너지 반환 효율 극대화.",
    youtubeReviews: [
      { label: "Endorphin Speed 5 리뷰", url: "https://www.youtube.com/results?search_query=saucony+endorphin+speed+5+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=사코니+엔도르핀+스피드+5+리뷰" },
      { label: "비교 영상", url: "https://www.youtube.com/results?search_query=endorphin+speed+5+vs+pegasus+comparison" },
    ],
  },
  {
    id: "nike-pegasus-42",
    brand: "Nike",
    model: "Pegasus 42",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40858/nike-pegasus-42-24827697-720.jpg",
    colorways: ["블랙/앤스라사이트", "화이트/퓨어플래티넘"],
    widthOptions: ["D", "2E"],
    heelDropMm: 10,
    stackHeightMm: 37,
    weightGramsM9: 286,
    priceUsd: 135,
    priceKrw: 159000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "나이키 공식 — 페가수스", url: "https://www.nike.com/kr/w/pegasus-shoes-8nexhzy7ok", isOfficial: true },
      { label: "무신사 — Nike", url: "https://www.musinsa.com/brand/nike", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%82%98%EC%9D%B4%ED%82%A4%20%ED%8E%98%EA%B0%80%EC%88%98%EC%8A%A4%2042", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Nike%20Pegasus%2042", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Nike%20Pegasus%2042", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/nike-pegasus-42",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [50, 85],
    heightRangeCm: [158, 185],
    primaryBodyTypes: ["mid_light", "mid_mid"],
    uses: ["daily", "long"],
    blurb: "드롭 10mm + React X 폼. 중형·경량 러너 전천후 만능 데일리.",
    scienceBasis: "React X 폼 — 드롭 10mm 힐스트라이커 충격 흡수 + 에너지 반환 균형.",
    youtubeReviews: [
      { label: "Pegasus 42 리뷰", url: "https://www.youtube.com/results?search_query=nike+pegasus+42+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=나이키+페가수스+42+리뷰" },
      { label: "Pegasus 42 vs 41 비교", url: "https://www.youtube.com/results?search_query=pegasus+42+vs+41+comparison" },
    ],
  },
  {
    id: "brooks-ghost-17",
    brand: "Brooks",
    model: "Ghost 17",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40767/brooks-ghost-17-23734399-720.jpg",
    colorways: ["블루/화이트", "블랙/이브닝"],
    widthOptions: ["B", "D", "2E", "4E"],
    heelDropMm: 10,
    stackHeightMm: 36,
    weightGramsM9: 289,
    priceUsd: 130,
    priceKrw: 169000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — Ghost 17", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EA%B3%A0%EC%8A%A4%ED%8A%B8+17", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%B8%8C%EB%A3%A9%EC%8A%A4%20%EA%B3%A0%EC%8A%A4%ED%8A%B8%2017", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Ghost%2017", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Ghost%2017", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/brooks-ghost-17",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [50, 92],
    heightRangeCm: [158, 192],
    primaryBodyTypes: ["mid_mid", "tall_mid"],
    uses: ["daily"],
    blurb: "폭 옵션 B~4E 전체. 중형·중량 러너 드롭 10mm 만능 데일리.",
    scienceBasis: "DNA Loft v3 폼 — 164-177cm 러너 보폭에서 충격 흡수·내구성 균형.",
    youtubeReviews: [
      { label: "Ghost 17 리뷰", url: "https://www.youtube.com/results?search_query=brooks+ghost+17+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+고스트+17+리뷰" },
      { label: "Ghost 17 vs Pegasus 42", url: "https://www.youtube.com/results?search_query=brooks+ghost+17+vs+nike+pegasus+42" },
    ],
  },
  {
    id: "nb-1080-v15",
    brand: "New Balance",
    model: "Fresh Foam X 1080 v15",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/41066/new-balance-1080-v-15-24327575-720.jpg",
    colorways: ["갤럭시", "블랙/화이트", "화이트/실버"],
    widthOptions: ["B", "D", "2E", "4E"],
    heelDropMm: 6,
    stackHeightMm: 40,
    weightGramsM9: 261,
    priceUsd: 175,
    priceKrw: 239000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "뉴발란스 공식몰", url: "https://www.newbalance.co.kr/ko/search?q=Fresh+Foam+1080", isOfficial: true },
      { label: "무신사 — New Balance", url: "https://www.musinsa.com/brand/newbalance", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%89%B4%EB%B0%9C%EB%9E%80%EC%8A%A4%201080%20v15", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=New%20Balance%20Fresh%20Foam%20X%201080%20v15", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=New%20Balance%20Fresh%20Foam%20X%201080%20v15", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/new-balance-1080-v-15",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 98],
    heightRangeCm: [155, 192],
    primaryBodyTypes: ["mid_mid", "mid_light"],
    uses: ["daily", "long"],
    blurb: "Infinion 폼 261g. 중형·중량 러너 최고급 쿠션 장거리 데일리.",
    scienceBasis: "Infinion 폼(TPEE+EVA) — 고탄성+내구성으로 중량 러너 장거리 충격 흡수 최적.",
    youtubeReviews: [
      { label: "1080 v15 리뷰", url: "https://www.youtube.com/results?search_query=new+balance+1080+v15+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=뉴발란스+1080+v15+리뷰" },
      { label: "1080 v15 vs Triumph 23", url: "https://www.youtube.com/results?search_query=nb+1080+v15+vs+triumph+23" },
    ],
  },
  {
    id: "saucony-triumph-23",
    brand: "Saucony",
    model: "Triumph 23",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40870/saucony-triumph-23-23515039-720.jpg",
    colorways: ["화이트/블루", "블랙"],
    widthOptions: ["D"],
    heelDropMm: 8,
    stackHeightMm: 42,
    weightGramsM9: 270,
    priceUsd: 165,
    priceKrw: 225000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "플릿러너 — 한국 공인딜러", url: "https://www.fleetrunner.co.kr/search?keyword=Triumph%2023", isOfficial: false },
      { label: "29CM 검색", url: "https://www.29cm.co.kr/search?keyword=Triumph%2023", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%82%AC%EC%BD%94%EB%8B%88%20%ED%8A%B8%EB%9D%BC%EC%9D%B4%EC%97%84%ED%94%84%2023", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Saucony%20Triumph%2023", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Saucony%20Triumph%2023", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/saucony-triumph-23",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 95],
    heightRangeCm: [155, 185],
    primaryBodyTypes: ["mid_mid", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "PWRRUN PB 42mm 스택. 중형 러너 최고급 쿠션 장거리.",
    scienceBasis: "PWRRUN PB 폼 — 중형 체중 분산 + 고스택으로 장거리 관절 보호.",
    youtubeReviews: [
      { label: "Triumph 23 리뷰", url: "https://www.youtube.com/results?search_query=saucony+triumph+23+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=사코니+트라이엄프+23+리뷰" },
      { label: "Triumph 23 vs 1080 v15", url: "https://www.youtube.com/results?search_query=triumph+23+vs+1080+v15" },
    ],
  },
  {
    id: "hoka-arahi-8",
    brand: "Hoka",
    model: "Arahi 8",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40854/hoka-arahi-8-23493841-720.jpg",
    colorways: ["블랙/화이트", "블루/오렌지"],
    widthOptions: ["D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 39,
    weightGramsM9: 259,
    priceUsd: 145,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "호카 공식몰 — 아라히", url: "https://www.hoka.com/ko-kr/running/road/arahi/", isOfficial: true },
      { label: "무신사 — Hoka", url: "https://www.musinsa.com/brand/hoka", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%ED%98%B8%EC%B9%B4%20%EC%95%84%EB%9D%BC%ED%9E%88%208", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Hoka%20Arahi%208", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Hoka%20Arahi%208", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/hoka-arahi-8",
    cushioning: 4,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [68, 115],
    heightRangeCm: [158, 185],
    primaryBodyTypes: ["mid_heavy", "tall_heavy"],
    uses: ["daily", "long"],
    blurb: "J-Frame 안정화 + 스택 39mm. 중형·고체중 평발 러너.",
    scienceBasis: "J-Frame — 내측 경질폼으로 과회내 제어, 고체중 러너 발목 안정화.",
    youtubeReviews: [
      { label: "Arahi 8 리뷰", url: "https://www.youtube.com/results?search_query=hoka+arahi+8+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=호카+아라히+8+리뷰" },
      { label: "Arahi 8 vs Kayano 32", url: "https://www.youtube.com/results?search_query=hoka+arahi+8+vs+kayano+32" },
    ],
  },
  {
    id: "brooks-adrenaline-gts-25",
    brand: "Brooks",
    model: "Adrenaline GTS 25",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40955/brooks-adrenaline-gts-25-24879218-720.jpg",
    colorways: ["블루/화이트", "블랙/화이트"],
    widthOptions: ["B", "D", "2E", "4E"],
    heelDropMm: 12,
    stackHeightMm: 36,
    weightGramsM9: 295,
    priceUsd: 135,
    priceKrw: 189000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — GTS 25 검색", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EC%95%84%EB%93%9C%EB%A0%88%EB%82%A0%EB%A6%B0+GTS+25", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%B8%8C%EB%A3%A9%EC%8A%A4%20%EC%95%84%EB%93%9C%EB%A0%88%EB%82%A0%EB%A6%B0%20GTS%2025", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Adrenaline%20GTS%2025", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Adrenaline%20GTS%2025", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/brooks-adrenaline-gts-25",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [65, 110],
    heightRangeCm: [158, 185],
    primaryBodyTypes: ["mid_heavy", "tall_heavy"],
    uses: ["daily"],
    blurb: "GuideRails 안정화 + 드롭 12mm. 중형·고체중 힐스트라이커.",
    scienceBasis: "GuideRails — 과도한 움직임 제어, 고체중 러너 무릎 부하 감소.",
    youtubeReviews: [
      { label: "Adrenaline GTS 25 리뷰", url: "https://www.youtube.com/results?search_query=brooks+adrenaline+gts+25+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+아드레날린+GTS+25+리뷰" },
      { label: "GTS 25 vs Kayano 32", url: "https://www.youtube.com/results?search_query=adrenaline+gts+25+vs+kayano+32" },
    ],
  },
  {
    id: "asics-gel-nimbus-27",
    brand: "Asics",
    model: "Gel-Nimbus 27",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40620/asics-gel-nimbus-27-22584818-720.jpg",
    colorways: ["블루/화이트", "블랙/카본"],
    widthOptions: ["D", "2E", "4E"],
    heelDropMm: 8,
    stackHeightMm: 44,
    weightGramsM9: 305,
    priceUsd: 165,
    priceKrw: 229000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰 — 젤님버스 27", url: "https://www.asics.co.kr/goods/search?search_text=Gel-Nimbus", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EC%8B%9D%EC%8A%A4%20%EC%A0%A4%20%EB%8B%98%EB%B2%84%EC%8A%A4%2027", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Gel-Nimbus%2027", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Gel-Nimbus%2027", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-gel-nimbus-27",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [65, 115],
    heightRangeCm: [165, 200],
    primaryBodyTypes: ["tall_mid", "mid_mid"],
    uses: ["daily", "long"],
    blurb: "스택 44mm 플래그십 쿠션. 대형·중량 러너 장거리 관절 보호.",
    scienceBasis: "FF Blast+ Eco 폼 + GEL — 고체중 러너 착지 충격 최대 흡수, Sinclair 2014 신장·관절 부하.",
    youtubeReviews: [
      { label: "Nimbus 27 리뷰", url: "https://www.youtube.com/results?search_query=asics+gel+nimbus+27+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+님버스+27+리뷰" },
      { label: "Nimbus 27 vs Bondi 9", url: "https://www.youtube.com/results?search_query=nimbus+27+vs+bondi+9+comparison" },
    ],
  },
  {
    id: "mizuno-wave-rider-29",
    brand: "Mizuno",
    model: "Wave Rider 29",
    imageUrl: "https://assets.mizuno.com/globalimages/shoes/running/u3gd250001_01.png",
    colorways: ["화이트/블루", "블랙/실버"],
    widthOptions: ["D", "2E"],
    heelDropMm: 10,
    stackHeightMm: 34,
    weightGramsM9: 258,
    priceUsd: 140,
    priceKrw: 195000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "미즈노 공식 코리아", url: "https://www.mizuno.com/ko-kr/search?q=wave+rider+29", isOfficial: true },
      { label: "무신사 — Mizuno", url: "https://www.musinsa.com/brand/mizuno", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%AF%B8%EC%A6%88%EB%85%B8%20%EC%9B%A8%EC%9D%B4%EB%B8%8C%20%EB%9D%BC%EC%9D%B4%EB%8D%94%2029", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Mizuno%20Wave%20Rider%2029", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Mizuno%20Wave%20Rider%2029", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/mizuno-wave-rider-29",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 90],
    heightRangeCm: [165, 195],
    primaryBodyTypes: ["tall_mid", "mid_mid"],
    uses: ["daily", "long"],
    blurb: "Wave 플레이트 + Enerzy NXT. 대형·중량 러너 데일리 드롭 10mm.",
    scienceBasis: "Wave 플레이트 — 대형 러너의 보폭 충격 분산, 드롭 10mm 힐스트라이커 최적.",
    youtubeReviews: [
      { label: "Wave Rider 29 리뷰", url: "https://www.youtube.com/results?search_query=mizuno+wave+rider+29+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=미즈노+웨이브라이더+29+리뷰" },
      { label: "Wave Rider 29 vs Ghost 17", url: "https://www.youtube.com/results?search_query=wave+rider+29+vs+ghost+17" },
    ],
  },
  {
    id: "adidas-ultraboost-25",
    brand: "Adidas",
    model: "Ultraboost 25",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40462/adidas-ultraboost-5-21818110-720.jpg",
    colorways: ["코어 블랙", "클라우드 화이트"],
    widthOptions: ["D"],
    heelDropMm: 10,
    stackHeightMm: 40,
    weightGramsM9: 330,
    priceUsd: 200,
    priceKrw: 279000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아디다스 공식몰", url: "https://www.adidas.co.kr/search?q=Ultraboost", isOfficial: true },
      { label: "무신사 — Adidas", url: "https://www.musinsa.com/brand/adidas", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EB%94%94%EB%8B%A4%EC%8A%A4%20%EC%9A%B8%ED%8A%B8%EB%9D%BC%EB%B6%80%EC%8A%A4%ED%8A%B8%2025", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Adidas%20Ultraboost%2025", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Adidas%20Ultraboost%2025", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/adidas-ultraboost-25",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [60, 100],
    heightRangeCm: [165, 195],
    primaryBodyTypes: ["tall_mid", "mid_mid"],
    uses: ["daily", "long"],
    blurb: "Light Boost 폼 프리미엄. 대형 러너 부드러운 장거리·일상겸용.",
    scienceBasis: "Light Boost TPU 폼 — 고체중 중형 러너 충격 흡수 + 에너지 반환.",
    youtubeReviews: [
      { label: "Ultraboost 25 리뷰", url: "https://www.youtube.com/results?search_query=adidas+ultraboost+25+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아디다스+울트라부스트+25+리뷰" },
      { label: "Ultraboost vs 1080 v15", url: "https://www.youtube.com/results?search_query=ultraboost+25+vs+1080+v15" },
    ],
  },
  {
    id: "nike-vaporfly-4",
    brand: "Nike",
    model: "ZoomX Vaporfly 4",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40754/nike-vaporfly-4-22860848-main.jpg",
    colorways: ["클라우드 화이트/볼트", "네온 옐로우"],
    widthOptions: ["D"],
    heelDropMm: 8,
    stackHeightMm: 42,
    weightGramsM9: 166,
    priceUsd: 265,
    priceKrw: 369000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "나이키 공식몰", url: "https://www.nike.com/kr/w/vaporfly-shoes-1gdj0z", isOfficial: true },
      { label: "무신사 — Nike", url: "https://www.musinsa.com/brand/nike", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%82%98%EC%9D%B4%ED%82%A4%20%EB%B2%A0%EC%9D%B4%ED%8D%BC%ED%94%8C%EB%9D%BC%EC%9D%B4%204", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Nike%20ZoomX%20Vaporfly%204", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Nike%20ZoomX%20Vaporfly%204", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/nike-vaporfly-4",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 82],
    heightRangeCm: [158, 192],
    primaryBodyTypes: ["tall_mid", "mid_light"],
    uses: ["racing"],
    blurb: "166g ZoomX 카본 레이싱화. 풀마라톤 기록 단축 최강.",
    scienceBasis: "ZoomX 폼 + 카본 플레이트 — 에너지 반환율 85%+, Hoogkamer 2018 4% 효율 향상.",
    youtubeReviews: [
      { label: "Vaporfly 4 리뷰", url: "https://www.youtube.com/results?search_query=nike+vaporfly+4+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=나이키+베이퍼플라이+4+리뷰" },
      { label: "Vaporfly 4 vs Adios Pro 4", url: "https://www.youtube.com/results?search_query=vaporfly+4+vs+adios+pro+4" },
    ],
  },
  {
    id: "hoka-bondi-9-wide",
    brand: "Hoka",
    model: "Bondi 9 (Wide)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40639/hoka-bondi-9-22560581-720.jpg",
    colorways: ["블랙/블랙", "화이트/화이트"],
    widthOptions: ["2E", "4E"],
    heelDropMm: 5,
    stackHeightMm: 40,
    weightGramsM9: 320,
    priceUsd: 175,
    priceKrw: 239000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "호카 공식몰 — 본디 와이드", url: "https://www.hoka.com/ko-kr/running/road/bondi/", isOfficial: true },
      { label: "무신사 — Hoka", url: "https://www.musinsa.com/brand/hoka", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%ED%98%B8%EC%B9%B4%20%EB%B3%B8%EB%94%94%20%EC%99%80%EC%9D%B4%EB%93%9C", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Hoka%20Bondi%209%20%28Wide%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Hoka%20Bondi%209%20%28Wide%29", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/hoka-bondi-9",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "flat"],
    weightRangeKg: [82, 140],
    heightRangeCm: [170, 200],
    primaryBodyTypes: ["tall_heavy", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "2E/4E 와이드 + 맥스쿠션. 대형·고체중·넓은발 러너 관절 보호.",
    scienceBasis: "맥시멀 쿠션 + 와이드 라스트 — 고체중 러너(82kg+) 착지 충격 최대 흡수.",
    youtubeReviews: [
      { label: "Bondi 9 Wide 리뷰", url: "https://www.youtube.com/results?search_query=hoka+bondi+9+wide+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=호카+본디+와이드+리뷰" },
      { label: "와이드 러닝화 비교", url: "https://www.youtube.com/results?search_query=hoka+bondi+9+wide+vs+regular" },
    ],
  },
  {
    id: "brooks-beast-24",
    brand: "Brooks",
    model: "Beast 24",
    imageUrl: "https://brooks-res.cloudinary.com/image/upload/b_white,c_pad,dpr_2.0,f_auto,h_490,q_auto,w_490/v1/eComm/110418_1D.jpg",
    colorways: ["블루/화이트", "블랙/실버"],
    widthOptions: ["2E", "4E"],
    heelDropMm: 12,
    stackHeightMm: 36,
    weightGramsM9: 370,
    priceUsd: 155,
    priceKrw: 215000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — Beast 24", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EB%B9%84%EC%8A%A4%ED%8A%B8+24", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%B8%8C%EB%A3%A9%EC%8A%A4%20%EB%B9%84%EC%8A%A4%ED%8A%B8%2024", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Beast%2024", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Beast%2024", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/brooks-beast-24",
    cushioning: 4,
    stability: "motion_control",
    footTypes: ["flat"],
    weightRangeKg: [90, 140],
    heightRangeCm: [170, 200],
    primaryBodyTypes: ["tall_heavy"],
    uses: ["daily"],
    blurb: "모션컨트롤 + 2E/4E. 대형·초고체중 과회내 러너 전용.",
    scienceBasis: "Extended Progressive Diagonal Rollbar — 심한 과회내 완전 제어, 90kg+ 러너.",
    youtubeReviews: [
      { label: "Brooks Beast 24 리뷰", url: "https://www.youtube.com/results?search_query=brooks+beast+24+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+비스트+24+리뷰" },
      { label: "모션컨트롤 비교", url: "https://www.youtube.com/results?search_query=brooks+beast+24+vs+adrenaline" },
    ],
  },
  {
    id: "mizuno-wave-sky-9",
    brand: "Mizuno",
    model: "Wave Sky 9",
    imageUrl: "https://assets.mizuno.com/globalimages/shoes/running/u3gd210001_01.png",
    colorways: ["화이트/블루", "블랙/실버"],
    widthOptions: ["D", "2E"],
    heelDropMm: 10,
    stackHeightMm: 38,
    weightGramsM9: 280,
    priceUsd: 150,
    priceKrw: 209000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "미즈노 공식 코리아", url: "https://www.mizuno.com/ko-kr/search?q=wave+sky+9", isOfficial: true },
      { label: "무신사 — Mizuno", url: "https://www.musinsa.com/brand/mizuno", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%AF%B8%EC%A6%88%EB%85%B8%20%EC%9B%A8%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%EC%B9%B4%EC%9D%B4%209", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Mizuno%20Wave%20Sky%209", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Mizuno%20Wave%20Sky%209", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/mizuno-wave-sky-9",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [60, 100],
    heightRangeCm: [165, 195],
    primaryBodyTypes: ["tall_mid", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "Wave 플레이트 + 고스택. 대형·중량 러너 프리미엄 쿠션.",
    scienceBasis: "Wave 플레이트 + 고스택 — 대형 러너 착지 충격 흡수 + 안정성.",
    youtubeReviews: [
      { label: "Wave Sky 9 리뷰", url: "https://www.youtube.com/results?search_query=mizuno+wave+sky+9+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=미즈노+웨이브스카이+9+리뷰" },
      { label: "비교 영상", url: "https://www.youtube.com/results?search_query=mizuno+wave+sky+9+vs+comparison" },
    ],
  },
  {
    id: "asics-superblast-2",
    brand: "Asics",
    model: "Superblast 2",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40450/asics-superblast-2-21749161-720.jpg",
    colorways: ["화이트/옐로우", "블랙/화이트"],
    widthOptions: ["D"],
    heelDropMm: 8,
    stackHeightMm: 45,
    weightGramsM9: 250,
    priceUsd: 200,
    priceKrw: 279000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰", url: "https://www.asics.co.kr/goods/search?search_text=Superblast", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EC%8B%9D%EC%8A%A4%20%EC%88%98%ED%8D%BC%EB%B8%94%EB%9D%BC%EC%8A%A4%ED%8A%B8%202", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Superblast%202", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Superblast%202", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-superblast-2",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [50, 95],
    heightRangeCm: [158, 195],
    primaryBodyTypes: ["tall_mid", "mid_mid"],
    uses: ["daily", "long", "racing"],
    blurb: "스택 45mm + 250g. 카본 없는 맥시멀 쿠션 일상·레이스 겸용.",
    scienceBasis: "FF Blast Turbo 폼 + 광폭 라스트 — 착지 안정성 + 에너지 반환 균형.",
    youtubeReviews: [
      { label: "Superblast 2 리뷰", url: "https://www.youtube.com/results?search_query=asics+superblast+2+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+수퍼블라스트+2+리뷰" },
      { label: "Superblast vs Nimbus 27", url: "https://www.youtube.com/results?search_query=superblast+2+vs+nimbus+27" },
    ],
  },
  {
    id: "nb-860-v15",
    brand: "New Balance",
    model: "860 v15",
    imageUrl: "https://image.msscdn.net/images/goods_img/20250219/4802737/4802737_17399226804049_500.jpg",
    colorways: ["화이트/블루", "블랙/화이트"],
    widthOptions: ["D", "2E", "4E"],
    heelDropMm: 10,
    stackHeightMm: 41,
    weightGramsM9: 295,
    priceUsd: 135,
    priceKrw: 179000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "뉴발란스 공식몰", url: "https://www.newbalance.co.kr/ko/search?q=860+v15", isOfficial: true },
      { label: "무신사 — New Balance", url: "https://www.musinsa.com/brand/newbalance", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%89%B4%EB%B0%9C%EB%9E%80%EC%8A%A4%20860%20v15", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=New%20Balance%20860%20v15", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=New%20Balance%20860%20v15", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/new-balance-860-v15",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [55, 95],
    heightRangeCm: [155, 190],
    primaryBodyTypes: ["mid_mid", "tall_mid"],
    uses: ["daily"],
    blurb: "Fresh Foam 안정화 + 4E 옵션. 중형·넓은발 과회내 러너.",
    scienceBasis: "Fresh Foam 안정화 포스트 — 과회내 제어 + 충격 흡수 병행.",
    youtubeReviews: [
      { label: "860 v15 리뷰", url: "https://www.youtube.com/results?search_query=new+balance+860+v15+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=뉴발란스+860+v15+리뷰" },
      { label: "860 vs GT-2000 비교", url: "https://www.youtube.com/results?search_query=nb+860+v15+vs+gt+2000+14" },
    ],
  },
  {
    id: "saucony-guide-18",
    brand: "Saucony",
    model: "Guide 18",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40636/saucony-guide-18-22687917-720.jpg",
    colorways: ["화이트/블루", "블랙/화이트"],
    widthOptions: ["D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 36,
    weightGramsM9: 265,
    priceUsd: 140,
    priceKrw: 189000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "플릿러너 — 한국 공인딜러", url: "https://www.fleetrunner.co.kr/search?keyword=Guide%2018", isOfficial: false },
      { label: "29CM 검색", url: "https://www.29cm.co.kr/search?keyword=Guide%2018", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%82%AC%EC%BD%94%EB%8B%88%20%EA%B0%80%EC%9D%B4%EB%93%9C%2018", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Saucony%20Guide%2018", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Saucony%20Guide%2018", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/saucony-guide-18",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [55, 90],
    heightRangeCm: [155, 185],
    primaryBodyTypes: ["mid_mid", "mid_heavy"],
    uses: ["daily"],
    blurb: "Center Path 안정화. 중형 평발 러너 가성비 안정화.",
    scienceBasis: "Center Path Technology — 착지 후 발 중심 정렬 유도, 과회내 자연 보정.",
    youtubeReviews: [
      { label: "Guide 18 리뷰", url: "https://www.youtube.com/results?search_query=saucony+guide+18+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=사코니+가이드+18+리뷰" },
      { label: "Guide vs Adrenaline GTS 비교", url: "https://www.youtube.com/results?search_query=saucony+guide+18+vs+adrenaline+gts" },
    ],
  },
  {
    id: "on-cloudrunner-3",
    brand: "On",
    model: "Cloudrunner 3",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/41111/on-cloudrunner-3-25074297-720.jpg",
    colorways: ["블랙/이클립스", "화이트/빙하"],
    widthOptions: ["D"],
    heelDropMm: 8,
    stackHeightMm: 34,
    weightGramsM9: 270,
    priceUsd: 155,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "온러닝 공식몰", url: "https://www.on.com/ko-kr/cloudrunner", isOfficial: true },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%98%A8%20%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C%EB%9F%AC%EB%84%88%203", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=On%20Cloudrunner%203", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=On%20Cloudrunner%203", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/on-cloudrunner-3",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 90],
    heightRangeCm: [155, 190],
    primaryBodyTypes: ["mid_mid", "tall_mid"],
    uses: ["daily"],
    blurb: "CloudTec + Helion 폼. 중형 러너 부드럽고 반응성 좋은 데일리.",
    scienceBasis: "CloudTec 레이어 — 착지 시 압축→에너지 반환, 중형 체중 최적화.",
    youtubeReviews: [
      { label: "Cloudrunner 3 리뷰", url: "https://www.youtube.com/results?search_query=on+cloudrunner+3+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=온러닝+클라우드러너+3+리뷰" },
      { label: "On vs Hoka 비교", url: "https://www.youtube.com/results?search_query=on+cloudrunner+3+vs+hoka+clifton" },
    ],
  },
  {
    id: "brooks-glycerin-22",
    brand: "Brooks",
    model: "Glycerin 22",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40658/brooks-glycerin-22-22723203-main.jpg",
    colorways: ["블루/화이트", "블랙/화이트"],
    widthOptions: ["B", "D", "2E", "4E"],
    heelDropMm: 10,
    stackHeightMm: 37,
    weightGramsM9: 295,
    priceUsd: 160,
    priceKrw: 199000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — Glycerin 22", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EA%B8%80%EB%A6%AC%EC%84%B8%EB%A6%B0+22", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%B8%8C%EB%A3%A9%EC%8A%A4%20%EA%B8%80%EB%A6%AC%EC%84%B8%EB%A6%B0%2022", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Glycerin%2022", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Glycerin%2022", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/brooks-glycerin-22",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [65, 110],
    heightRangeCm: [165, 200],
    primaryBodyTypes: ["tall_heavy", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "DNA Tuned 고쿠션 + B~4E. 대형·고체중 중립 러너 프리미엄 장거리.",
    scienceBasis: "DNA Tuned 폼 — 체중별 맞춤 반응성, 고체중 러너 관절 보호 극대화.",
    youtubeReviews: [
      { label: "Glycerin 22 리뷰", url: "https://www.youtube.com/results?search_query=brooks+glycerin+22+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+글리세린+22+리뷰" },
      { label: "Glycerin vs 1080 v15", url: "https://www.youtube.com/results?search_query=glycerin+22+vs+1080+v15" },
    ],
  },
  {
    id: "nike-infinity-run-4",
    brand: "Nike",
    model: "InfinityRN 4",
    imageUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7e01e069-9b9f-47fc-ad9e-4d5a0d1c2285/infinity-run-4-road-running-shoes-XxRvxG.png",
    colorways: ["블랙/앤스라사이트", "화이트/퓨어플래티넘"],
    widthOptions: ["D", "2E"],
    heelDropMm: 9,
    stackHeightMm: 37,
    weightGramsM9: 290,
    priceUsd: 160,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "나이키 공식몰", url: "https://www.nike.com/kr/w/infinity-run-shoes-56j6z", isOfficial: true },
      { label: "무신사 — Nike", url: "https://www.musinsa.com/brand/nike", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%82%98%EC%9D%B4%ED%82%A4%20%EC%9D%B8%ED%94%BC%EB%8B%88%ED%8B%B0%EB%9F%B0%204", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Nike%20InfinityRN%204", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Nike%20InfinityRN%204", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/nike-infinity-run-4",
    cushioning: 4,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [55, 100],
    heightRangeCm: [158, 195],
    primaryBodyTypes: ["tall_heavy", "mid_heavy"],
    uses: ["daily"],
    blurb: "React X 안정화 + 드롭 9mm. 대형·고체중 평발 힐스트라이커.",
    scienceBasis: "React X + 안정화 플레이트 — 과회내 보정 + 에너지 반환 균형.",
    youtubeReviews: [
      { label: "InfinityRN 4 리뷰", url: "https://www.youtube.com/results?search_query=nike+infinityrn+4+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=나이키+인피니티런+4+리뷰" },
      { label: "InfinityRN 4 vs Adrenaline GTS", url: "https://www.youtube.com/results?search_query=infinityrn+4+vs+adrenaline+gts" },
    ],
  },
  {
    id: "mizuno-wave-inspire-22",
    brand: "Mizuno",
    model: "Wave Inspire 22",
    imageUrl: "https://assets.mizuno.com/globalimages/shoes/running/u3gb230001_01.png",
    colorways: ["블루/화이트", "블랙/실버"],
    widthOptions: ["D", "2E"],
    heelDropMm: 12,
    stackHeightMm: 38,
    weightGramsM9: 285,
    priceUsd: 140,
    priceKrw: 195000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "미즈노 공식 코리아", url: "https://www.mizuno.com/ko-kr/search?q=wave+inspire+22", isOfficial: true },
      { label: "무신사 — Mizuno", url: "https://www.musinsa.com/brand/mizuno", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%AF%B8%EC%A6%88%EB%85%B8%20%EC%9B%A8%EC%9D%B4%EB%B8%8C%20%EC%9D%B8%EC%8A%A4%ED%8C%8C%EC%9D%B4%EC%96%B4%2022", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Mizuno%20Wave%20Inspire%2022", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Mizuno%20Wave%20Inspire%2022", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/mizuno-wave-inspire-22",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [65, 110],
    heightRangeCm: [165, 200],
    primaryBodyTypes: ["tall_heavy", "mid_heavy"],
    uses: ["daily"],
    blurb: "Fan Wave 안정화 + 드롭 12mm. 대형·고체중 평발 힐스트라이커.",
    scienceBasis: "Fan Wave 플레이트 — 과회내 시 내측 지지 + 충격 분산 동시 수행.",
    youtubeReviews: [
      { label: "Wave Inspire 22 리뷰", url: "https://www.youtube.com/results?search_query=mizuno+wave+inspire+22+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=미즈노+웨이브인스파이어+22+리뷰" },
      { label: "비교 영상", url: "https://www.youtube.com/results?search_query=mizuno+wave+inspire+22+vs+comparison" },
    ],
  },
  {
    id: "asics-novablast-5",
    brand: "Asics",
    model: "Novablast 5",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40608/asics-novablast-5-22312736-720.jpg",
    colorways: ["블루/화이트", "블랙/화이트", "옐로우/그린"],
    widthOptions: ["D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 42,
    weightGramsM9: 255,
    priceUsd: 140,
    priceKrw: 179000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰 — 노바블라스트 5", url: "https://www.asics.co.kr/c/novablast-5", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EC%8B%9D%EC%8A%A4+%EB%85%B8%EB%B0%94%EB%B8%94%EB%9D%BC%EC%8A%A4%ED%8A%B8+5", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Novablast%205", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Novablast%205", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-novablast-5",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 85],
    heightRangeCm: [148, 192],
    primaryBodyTypes: ["mid_light", "mid_mid", "small_mid"],
    uses: ["daily", "long", "tempo"],
    blurb: "FF BLAST MAX 폼 255g. 한국 러너 국민 데일리 — 쿠션·반발력·무게 균형 최상.",
    scienceBasis: "FF BLAST MAX(발포 TPE) — 착지 에너지 반환 + 소프트 착지 동시 구현. 드롭 8mm 중형 러너 미드풋/힐스트라이크 모두 수용.",
    youtubeReviews: [
      { label: "Novablast 5 리뷰", url: "https://www.youtube.com/results?search_query=asics+novablast+5+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+노바블라스트+5+리뷰" },
      { label: "Novablast 5 vs Superblast 2", url: "https://www.youtube.com/results?search_query=novablast+5+vs+superblast+2" },
    ],
  },
  {
    id: "asics-gel-cumulus-27",
    brand: "Asics",
    model: "Gel-Cumulus 27",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40699/asics-gel-cumulus-27-22918744-720.jpg",
    colorways: ["블랙/코랄 리프", "화이트/블루"],
    widthOptions: ["D", "2E", "4E"],
    heelDropMm: 8,
    stackHeightMm: 41,
    weightGramsM9: 261,
    priceUsd: 140,
    priceKrw: 169000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰 — 큐물러스", url: "https://www.asics.co.kr/goods/search?search_text=Gel-Cumulus", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%95%84%EC%8B%9D%EC%8A%A4+%EC%A0%A4+%ED%81%90%EB%A9%80%EB%9F%AC%EC%8A%A4+27", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Gel-Cumulus%2027", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Gel-Cumulus%2027", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-gel-cumulus-27",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [50, 85],
    heightRangeCm: [150, 185],
    primaryBodyTypes: ["mid_light", "mid_mid"],
    uses: ["daily", "long"],
    blurb: "FF Blast+ 41mm 스택 261g. 중형 러너 부드럽고 믿음직한 만능 데일리.",
    scienceBasis: "FF Blast+ + GEL — 착지 충격 분산 + 에너지 반환. 스택 41mm로 중장거리 관절 보호 (van Gent 2007).",
    youtubeReviews: [
      { label: "Gel-Cumulus 27 리뷰", url: "https://www.youtube.com/results?search_query=asics+gel+cumulus+27+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+큐물러스+27+리뷰" },
      { label: "Cumulus 27 vs Nimbus 27", url: "https://www.youtube.com/results?search_query=cumulus+27+vs+nimbus+27" },
    ],
  },
  {
    id: "hoka-mach-6",
    brand: "Hoka",
    model: "Mach 6",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40333/hoka-mach-6-21454844-main.jpg",
    colorways: ["블루/에메랄드", "블랙/화이트"],
    widthOptions: ["D"],
    heelDropMm: 5,
    stackHeightMm: 37,
    weightGramsM9: 232,
    priceUsd: 145,
    priceKrw: 189000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "호카 공식몰 — Mach 6", url: "https://www.hoka.com/ko-kr/running/road/mach/", isOfficial: true },
      { label: "무신사 — Hoka", url: "https://www.musinsa.com/brand/hoka", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%ED%98%B8%EC%B9%B4+%EB%A7%88%ED%95%98+6", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Hoka%20Mach%206", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Hoka%20Mach%206", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/hoka-mach-6",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 80],
    heightRangeCm: [148, 178],
    primaryBodyTypes: ["small_light", "mid_light", "small_mid"],
    uses: ["tempo", "daily"],
    blurb: "Supercritical EVA 232g + 드롭 5mm. 소형·경량 러너 경쾌한 템포·데일리 겸용.",
    scienceBasis: "Supercritical EVA 폼 — 저중량 고반발. 드롭 5mm로 소형 러너 미드풋 착지 유도 (Heiderscheit 2011).",
    youtubeReviews: [
      { label: "Hoka Mach 6 리뷰", url: "https://www.youtube.com/results?search_query=hoka+mach+6+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=호카+마하+6+리뷰" },
      { label: "Mach 6 vs Clifton 10", url: "https://www.youtube.com/results?search_query=hoka+mach+6+vs+clifton+10" },
    ],
  },
  {
    id: "saucony-ride-18",
    brand: "Saucony",
    model: "Ride 18",
    imageUrl: "https://gazellesports.com/cdn/shop/files/S21000-100_1.jpg?v=1734443649",
    colorways: ["화이트/블루", "블랙/레드"],
    widthOptions: ["D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 37,
    weightGramsM9: 274,
    priceUsd: 140,
    priceKrw: 205000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "플릿러너 — 한국 공인딜러", url: "https://www.fleetrunner.co.kr/search?keyword=Ride%2018", isOfficial: false },
      { label: "29CM 검색", url: "https://www.29cm.co.kr/search?keyword=Ride%2018", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%82%AC%EC%BD%94%EB%8B%88+%EB%9D%BC%EC%9D%B4%EB%93%9C+18", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Saucony%20Ride%2018", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Saucony%20Ride%2018", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/saucony-ride-18",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 90],
    heightRangeCm: [155, 185],
    primaryBodyTypes: ["mid_mid", "mid_light", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "PWRRUN+ 274g. 중형 러너 플래그십 중립 데일리 — 부드럽고 내구성 강함.",
    scienceBasis: "PWRRUN+ 폼(고밀도 발포 폴리우레탄) — 고내구성 + 소프트 착지. 드롭 8mm 중형 러너 힐·미드풋 착지 모두 수용.",
    youtubeReviews: [
      { label: "Ride 18 리뷰", url: "https://www.youtube.com/results?search_query=saucony+ride+18+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=사코니+라이드+18+리뷰" },
      { label: "Ride 18 vs Pegasus 42", url: "https://www.youtube.com/results?search_query=saucony+ride+18+vs+pegasus+42" },
    ],
  },
  {
    id: "nike-pegasus-plus",
    brand: "Nike",
    model: "Pegasus Plus",
    imageUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e447a700-9a18-4a16-8d68-b955ca35d9f7/pegasus-plus-road-running-shoes-HB4KlG.png",
    colorways: ["화이트/볼트", "블랙/앤스라사이트"],
    widthOptions: ["D"],
    heelDropMm: 10,
    stackHeightMm: 35,
    weightGramsM9: 244,
    priceUsd: 160,
    priceKrw: 209000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "나이키 공식몰 — 페가수스 플러스", url: "https://www.nike.com/kr/w/pegasus-shoes-8nexhzy7ok", isOfficial: true },
      { label: "무신사 — Nike", url: "https://www.musinsa.com/brand/nike", isOfficial: false },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EB%82%98%EC%9D%B4%ED%82%A4+%ED%8E%98%EA%B0%80%EC%88%98%EC%8A%A4+%ED%94%8C%EB%9F%AC%EC%8A%A4", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Nike%20Pegasus%20Plus", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Nike%20Pegasus%20Plus", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/nike-pegasus-plus",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 78],
    heightRangeCm: [150, 185],
    primaryBodyTypes: ["mid_light", "small_light", "small_mid"],
    uses: ["tempo", "daily", "racing"],
    blurb: "풀렝스 ZoomX 244g. 경량 러너 페가수스 라인 최고 반발력 템포화.",
    scienceBasis: "ZoomX 폼(발포 PEBA) — 플레이트 없이 85%+ 에너지 반환. 드롭 10mm 경량 러너 힐스트라이크 충격 분산 최적.",
    youtubeReviews: [
      { label: "Pegasus Plus 리뷰", url: "https://www.youtube.com/results?search_query=nike+pegasus+plus+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=나이키+페가수스+플러스+리뷰" },
      { label: "Pegasus Plus vs Pegasus 42", url: "https://www.youtube.com/results?search_query=pegasus+plus+vs+pegasus+42" },
    ],
  },
  {
    id: "on-cloudmonster-2",
    brand: "On",
    model: "Cloudmonster 2",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40327/on-cloudmonster-2-21369854-720.jpg",
    colorways: ["아이스/플래시", "블랙/이클립스"],
    widthOptions: ["D"],
    heelDropMm: 6,
    stackHeightMm: 35,
    weightGramsM9: 295,
    priceUsd: 170,
    priceKrw: 229000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "온러닝 공식몰 — Cloudmonster 2", url: "https://www.on.com/ko-kr/cloudmonster", isOfficial: true },
      { label: "KREAM (리셀·정품검수)", url: "https://kream.co.kr/search?keyword=%EC%98%A8+%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C%EB%AA%AC%EC%8A%A4%ED%84%B0+2", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=On%20Cloudmonster%202", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=On%20Cloudmonster%202", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/on-cloudmonster-2",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 95],
    heightRangeCm: [155, 190],
    primaryBodyTypes: ["mid_mid", "tall_mid"],
    uses: ["daily", "long"],
    blurb: "CloudTec Phase 35mm + 295g. On 라인업 최고 쿠션 — 중형 러너 부드러운 장거리.",
    scienceBasis: "CloudTec Phase — 착지 시 단계적 클라우드 압축으로 충격 흡수 후 탄성 에너지 반환. 중형 체중 장거리 관절 보호.",
    youtubeReviews: [
      { label: "Cloudmonster 2 리뷰", url: "https://www.youtube.com/results?search_query=on+cloudmonster+2+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=온러닝+클라우드몬스터+2+리뷰" },
      { label: "Cloudmonster 2 vs Clifton 10", url: "https://www.youtube.com/results?search_query=cloudmonster+2+vs+clifton+10" },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // 여성 전용 라스트(Women's Last) 모델 — 2025~2026 현행 판매
  // 근거: Wunderlich & Cavanagh (2001) — 여성 발은 남성 발의 축소판이 아님
  //       (좁은 힐 + 낮은 발등 볼륨 + 다른 폼 경도). 여성 선택 시에만 노출됨.
  //       무게/가격은 여성(WW) 기준. 한국 여성 '좁은힐+넓은앞볼' 콤비네이션 발 고려해 폭 옵션 표기.
  // ════════════════════════════════════════════════════════════════
  {
    id: "brooks-ghost-17-w",
    brand: "Brooks",
    model: "Ghost 17 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40767/brooks-ghost-17-23734399-720.jpg",
    colorways: ["피치/라벤더", "화이트/실버"],
    widthOptions: ["B", "D", "2E"],
    heelDropMm: 10,
    stackHeightMm: 36,
    weightGramsM9: 252,
    priceUsd: 130,
    priceKrw: 169000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — 고스트 17 여성", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EA%B3%A0%EC%8A%A4%ED%8A%B8+17", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (정품검수)", url: "https://kream.co.kr/search?keyword=브룩스+고스트+17+여성", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Ghost%2017%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Ghost%2017%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/brooks-ghost-17",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 75],
    heightRangeCm: [150, 175],
    primaryBodyTypes: ["small_mid", "mid_light", "mid_mid"],
    uses: ["daily"],
    blurb: "여성 전용 라스트 + 폭 B~2E. 좁은 힐로 뒤꿈치 헛도는 느낌 없는 만능 데일리.",
    scienceBasis: "여성 발은 같은 길이라도 뒤꿈치가 좁다(Wunderlich & Cavanagh 2001). Ghost 여성 라스트는 힐을 좁히고 발등을 낮춰 고정력을 높임.",
    genderFit: "womens_last",
    womensWidths: ["B", "D", "2E"],
    forefootFit: "standard",
    instepVolume: "low",
    genderNote: "여성 전용 라스트(좁은 힐·낮은 발등). 무게·가격은 여성(WW) 기준. 한국 여성 넓은 앞볼이면 2E 폭 권장.",
    youtubeReviews: [
      { label: "Ghost 17 여성 리뷰", url: "https://www.youtube.com/results?search_query=brooks+ghost+17+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+고스트+17+여성+리뷰" },
      { label: "여성 데일리화 비교", url: "https://www.youtube.com/results?search_query=best+womens+daily+running+shoe+2025" },
    ],
  },
  {
    id: "brooks-glycerin-22-w",
    brand: "Brooks",
    model: "Glycerin 22 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40658/brooks-glycerin-22-22723203-main.jpg",
    colorways: ["로즈/그레이", "블랙/핑크"],
    widthOptions: ["B", "D"],
    heelDropMm: 10,
    stackHeightMm: 37,
    weightGramsM9: 258,
    priceUsd: 165,
    priceKrw: 199000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — 글리세린 22 여성", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EA%B8%80%EB%A6%AC%EC%84%B8%EB%A6%B0+22", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (정품검수)", url: "https://kream.co.kr/search?keyword=브룩스+글리세린+22+여성", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Glycerin%2022%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Glycerin%2022%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/brooks-glycerin-22",
    cushioning: 5,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [48, 85],
    heightRangeCm: [152, 178],
    primaryBodyTypes: ["mid_light", "mid_mid", "small_mid"],
    uses: ["daily", "long"],
    blurb: "여성 라스트 + DNA Tuned 맥시멀 쿠션. 장거리·회복주 폭신함 끝판왕.",
    scienceBasis: "여성용은 폼 경도를 낮춰(softer durometer) 가벼운 체중대에서도 충분히 압축되도록 튜닝. 여성 평균 체중에서 과한 반발 없이 충격 흡수.",
    genderFit: "womens_last",
    womensWidths: ["B", "D"],
    forefootFit: "standard",
    instepVolume: "low",
    genderNote: "여성 전용 라스트 + 여성용 폼 경도. 발등이 높은 편이면 끈 압박 확인 권장.",
    youtubeReviews: [
      { label: "Glycerin 22 여성 리뷰", url: "https://www.youtube.com/results?search_query=brooks+glycerin+22+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+글리세린+22+여성+리뷰" },
      { label: "여성 쿠션화 비교", url: "https://www.youtube.com/results?search_query=best+womens+max+cushion+running+shoe" },
    ],
  },
  {
    id: "brooks-adrenaline-gts-25-w",
    brand: "Brooks",
    model: "Adrenaline GTS 25 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40955/brooks-adrenaline-gts-25-24879218-720.jpg",
    colorways: ["블루/코랄", "그레이/민트"],
    widthOptions: ["B", "D", "2E"],
    heelDropMm: 12,
    stackHeightMm: 36,
    weightGramsM9: 258,
    priceUsd: 140,
    priceKrw: 189000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "브룩스 공식 코리아 — 아드레날린 GTS 25 여성", url: "https://brooksrunning.co.kr/product/search.html?keyword=%EC%95%84%EB%93%9C%EB%A0%88%EB%82%A0%EB%A6%B0", isOfficial: true },
      { label: "무신사 — Brooks", url: "https://www.musinsa.com/brand/brooksrunning", isOfficial: false },
      { label: "KREAM (정품검수)", url: "https://kream.co.kr/search?keyword=브룩스+아드레날린+GTS+25+여성", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Brooks%20Adrenaline%20GTS%2025%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Brooks%20Adrenaline%20GTS%2025%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/brooks-adrenaline-gts-25",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [48, 82],
    heightRangeCm: [150, 176],
    primaryBodyTypes: ["small_mid", "mid_light", "mid_mid"],
    uses: ["daily"],
    blurb: "여성 라스트 + GuideRails 안정화. 평발·과회내 여성 러너 무릎 보호 1순위.",
    scienceBasis: "여성은 동적 Q앵글이 커 무릎 외전·과회내가 크다(Ferber 2003). GuideRails가 과도한 무릎 내측 움직임을 제어 — 여성 PFPS(남성의 2배, Taunton 2002) 부담 완화.",
    genderFit: "womens_last",
    womensWidths: ["B", "D", "2E"],
    forefootFit: "standard",
    instepVolume: "low",
    genderNote: "여성 전용 라스트 + 안정화. 평발·무릎 안쪽 통증 있는 여성에게 우선 추천.",
    youtubeReviews: [
      { label: "Adrenaline GTS 25 여성 리뷰", url: "https://www.youtube.com/results?search_query=brooks+adrenaline+gts+25+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=브룩스+아드레날린+25+여성+리뷰" },
      { label: "여성 안정화 비교", url: "https://www.youtube.com/results?search_query=best+womens+stability+running+shoe+2025" },
    ],
  },
  {
    id: "asics-gel-kayano-32-w",
    brand: "Asics",
    model: "Gel-Kayano 32 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40809/asics-gel-kayano-32-23240127-720.jpg",
    colorways: ["화이트/로즈골드", "퓨어실버/핑크"],
    widthOptions: ["B", "D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 40,
    weightGramsM9: 258,
    priceUsd: 165,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰(asics.co.kr) — 젤카야노 32 우먼", url: "https://www.asics.co.kr/p/19974", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "KREAM (정품검수)", url: "https://kream.co.kr/search?keyword=아식스+젤카야노+32+여성", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Gel-Kayano%2032%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Gel-Kayano%2032%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/asics-gel-kayano-32",
    cushioning: 4,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [50, 85],
    heightRangeCm: [152, 178],
    primaryBodyTypes: ["mid_mid", "mid_heavy", "small_mid"],
    uses: ["daily", "long"],
    blurb: "여성 라스트 + 4D Guidance 안정화 + 맥시멀 쿠션. 과회내 여성 장거리 최적.",
    scienceBasis: "여성 평발·과회내 러너에게 4D Guidance System이 회내 속도를 늦춤(Richards 2009: 발타입별 안정화 매칭). 여성 라스트로 힐 고정력 확보.",
    genderFit: "womens_last",
    womensWidths: ["B", "D", "2E"],
    forefootFit: "standard",
    instepVolume: "standard",
    genderNote: "여성 전용 라스트 + 안정화. 평발 여성의 장거리 무릎·발목 보호용. 넓은 앞볼이면 2E 권장.",
    youtubeReviews: [
      { label: "Gel-Kayano 32 여성 리뷰", url: "https://www.youtube.com/results?search_query=asics+gel+kayano+32+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+카야노+32+여성+리뷰" },
      { label: "여성 안정화 비교", url: "https://www.youtube.com/results?search_query=kayano+32+vs+adrenaline+gts+25" },
    ],
  },
  {
    id: "nike-pegasus-42-w",
    brand: "Nike",
    model: "Pegasus 42 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40858/nike-pegasus-42-24827697-720.jpg",
    colorways: ["펄 핑크/화이트", "블랙/멀티"],
    widthOptions: ["B", "D"],
    heelDropMm: 10,
    stackHeightMm: 37,
    weightGramsM9: 238,
    priceUsd: 140,
    priceKrw: 159000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "나이키 공식몰 — 페가수스 42 여성", url: "https://www.nike.com/kr/w?q=%ED%8E%98%EA%B0%80%EC%88%98%EC%8A%A4+42", isOfficial: true },
      { label: "무신사 — Nike", url: "https://www.musinsa.com/brand/nike", isOfficial: false },
      { label: "KREAM (정품검수)", url: "https://kream.co.kr/search?keyword=나이키+페가수스+42+여성", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Nike%20Pegasus%2042%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Nike%20Pegasus%2042%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/nike-pegasus-42",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 72],
    heightRangeCm: [150, 174],
    primaryBodyTypes: ["small_light", "small_mid", "mid_light"],
    uses: ["daily", "long"],
    blurb: "여성 전용 라스트 + ReactX 폼. 단, 앞볼(토박스)이 좁아 발볼 넓으면 비추.",
    scienceBasis: "여성 라스트로 힐을 좁혀 고정력↑. 다만 토박스가 좁아(narrow forefoot) 한국인 넓은 앞볼엔 끼일 수 있음 — 좁은~보통 발볼 여성에게 적합.",
    genderFit: "womens_last",
    womensWidths: ["B", "D"],
    forefootFit: "narrow",
    instepVolume: "low",
    genderNote: "여성 전용 라스트지만 앞볼이 좁음. 한국인 넓은 발볼이면 Ghost·Glycerin 여성 권장.",
    youtubeReviews: [
      { label: "Pegasus 42 여성 리뷰", url: "https://www.youtube.com/results?search_query=nike+pegasus+42+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=나이키+페가수스+42+여성+리뷰" },
      { label: "페가수스 42 핏 가이드", url: "https://www.youtube.com/results?search_query=nike+pegasus+42+fit+narrow" },
    ],
  },
  {
    id: "saucony-guide-18-w",
    brand: "Saucony",
    model: "Guide 18 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40636/saucony-guide-18-22687917-720.jpg",
    colorways: ["라일락/오로라", "포그/핑크"],
    widthOptions: ["B", "D"],
    heelDropMm: 8,
    stackHeightMm: 36,
    weightGramsM9: 227,
    priceUsd: 140,
    priceKrw: 189000,
    krAvailability: "kr_parallel",
    buyLinks: [
      { label: "플릿러너 — 한국 공인딜러", url: "https://www.fleetrunner.co.kr/search?keyword=Guide%2018%20", isOfficial: false },
      { label: "29CM 검색", url: "https://www.29cm.co.kr/search?keyword=Guide%2018%20", isOfficial: false },
      { label: "KREAM (정품검수)", url: "https://kream.co.kr/search?keyword=사코니+가이드+18+여성", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Saucony%20Guide%2018%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Saucony%20Guide%2018%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/saucony-guide-18",
    cushioning: 3,
    stability: "stability",
    footTypes: ["flat", "neutral"],
    weightRangeKg: [45, 78],
    heightRangeCm: [150, 175],
    primaryBodyTypes: ["small_mid", "mid_light", "small_light"],
    uses: ["daily"],
    blurb: "여성 라스트 + 경량 안정화(227g). 가벼운 평발 여성의 데일리 안정화.",
    scienceBasis: "CenterPath 지오메트리로 과회내를 부드럽게 제어 — 여성 동적 Q앵글(Ferber 2003) 대응. 안정화 중 경량이라 입문 여성에게 부담 적음.",
    genderFit: "womens_last",
    womensWidths: ["B", "D"],
    forefootFit: "standard",
    instepVolume: "low",
    genderNote: "여성 전용 라스트 + 경량 안정화. 평발이지만 무거운 신발이 싫은 여성에게 적합.",
    youtubeReviews: [
      { label: "Guide 18 여성 리뷰", url: "https://www.youtube.com/results?search_query=saucony+guide+18+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=사코니+가이드+18+여성+리뷰" },
      { label: "경량 안정화 비교", url: "https://www.youtube.com/results?search_query=saucony+guide+18+vs+brooks+adrenaline" },
    ],
  },
  {
    id: "hoka-clifton-10-w",
    brand: "Hoka",
    model: "Clifton 10 (여성)",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/40691/hoka-clifton-10-22918659-720.jpg",
    colorways: ["페일 모브/피치", "화이트/로즈"],
    widthOptions: ["B", "D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 43,
    weightGramsM9: 224,
    priceUsd: 150,
    priceKrw: 199000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "호카 공식몰 — 클리프턴 10 여성", url: "https://www.hoka.com/ko/kr/women-clifton/", isOfficial: true },
      { label: "무신사 — Hoka", url: "https://www.musinsa.com/brand/hoka", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Hoka%20Clifton%2010%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Hoka%20Clifton%2010%20%28%EC%97%AC%EC%84%B1%29", isOfficial: false },
    ],
    gender: "female",
    sourceUrl: "https://runrepeat.com/hoka-clifton-10",
    cushioning: 4,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 80],
    heightRangeCm: [150, 176],
    primaryBodyTypes: ["small_light", "small_mid", "mid_light"],
    uses: ["daily", "long"],
    blurb: "여성 핏 + 224g 경량 맥시멀 쿠션. 좁은 힐로 빠지지 않는 푹신한 데일리.",
    scienceBasis: "여성 평균 발볼에 맞춘 좁은 힐 + 낮은 발등 볼륨(Wunderlich 2001). 두꺼운 스택이지만 경량이라 가벼운 체중대 여성에게 안정적.",
    genderFit: "womens_last",
    womensWidths: ["B", "D", "2E"],
    forefootFit: "standard",
    instepVolume: "low",
    genderNote: "여성 핏(좁은 힐). 넓은 앞볼 여성은 2E(Wide) 옵션 선택.",
    youtubeReviews: [
      { label: "Clifton 10 여성 리뷰", url: "https://www.youtube.com/results?search_query=hoka+clifton+10+women+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=호카+클리프턴+10+여성+리뷰" },
      { label: "여성 쿠션화 비교", url: "https://www.youtube.com/results?search_query=hoka+clifton+10+vs+brooks+glycerin" },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // 가성비 입문 모델 (15만원 이하) — 2025~2026 현행 판매
  // 가격은 한국 정가/스트리트가 기준 근사치. 매물은 네이버 쇼핑(집계)로 연결.
  // ════════════════════════════════════════════════════════════════
  {
    id: "puma-velocity-nitro-3",
    brand: "Puma",
    model: "Velocity NITRO 3",
    imageUrl: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/377748/01/sv01/fnd/PNA/fmt/png/Velocity-NITRO-3-Mens-Running-Shoes",
    colorways: ["블랙/화이트", "쿨 블루"],
    widthOptions: ["D"],
    heelDropMm: 10,
    stackHeightMm: 30,
    weightGramsM9: 280,
    priceUsd: 110,
    priceKrw: 139000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "푸마 공식몰", url: "https://kr.puma.com/kr/ko/search?q=벨로시티+니트로", isOfficial: true },
      { label: "무신사 — Puma", url: "https://www.musinsa.com/brand/puma", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Puma%20Velocity%20NITRO%203", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Puma%20Velocity%20NITRO%203", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/puma-velocity-nitro-3",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [50, 85],
    heightRangeCm: [155, 185],
    primaryBodyTypes: ["mid_mid", "mid_light", "tall_mid"],
    uses: ["daily", "long"],
    blurb: "약 14만원 가성비 — NITRO 폼으로 입문~중급 데일리에 충분한 쿠션과 반발.",
    scienceBasis: "NITRO 발포 미드솔 — 가격대 대비 쿠션·반발 균형이 좋아 입문 러너 데일리에 적합.",
    forefootFit: "standard",
    instepVolume: "standard",
    youtubeReviews: [
      { label: "Velocity NITRO 3 리뷰", url: "https://www.youtube.com/results?search_query=puma+velocity+nitro+3+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=푸마+벨로시티+니트로+3+리뷰" },
      { label: "가성비 러닝화 비교", url: "https://www.youtube.com/results?search_query=best+budget+running+shoe+2025" },
    ],
  },
  {
    id: "decathlon-kiprun-ks500-2",
    brand: "Decathlon",
    model: "KIPRUN KS500 2",
    imageUrl: "https://cdn.dsmcdn.com/ty1577/prod/QC/20241002/16/dd334405-4570-3637-a319-1ba6e66f99c4/1_org_zoom.jpg",
    colorways: ["카본 그레이", "블랙"],
    widthOptions: ["D"],
    heelDropMm: 8,
    stackHeightMm: 34,
    weightGramsM9: 285,
    priceUsd: 80,
    priceKrw: 99000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "데카트론 공식몰 — KIPRUN KS500", url: "https://www.decathlon.co.kr/search?q=KIPRUN+KS500", isOfficial: true },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Decathlon%20KIPRUN%20KS500%202", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Decathlon%20KIPRUN%20KS500%202", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/kiprun-ks500",
    cushioning: 3,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [55, 90],
    heightRangeCm: [160, 188],
    primaryBodyTypes: ["mid_mid", "tall_mid", "mid_heavy"],
    uses: ["daily", "long"],
    blurb: "약 10만원 — 데카트론 인기 가성비 쿠션화. 입문 장거리·조깅에 무난.",
    scienceBasis: "두꺼운 EVA 미드솔 + 8mm 드롭 — 입문 러너의 조깅·장거리에 충격 흡수 충분.",
    forefootFit: "standard",
    instepVolume: "standard",
    youtubeReviews: [
      { label: "KIPRUN KS500 리뷰", url: "https://www.youtube.com/results?search_query=kiprun+ks500+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=데카트론+킵런+KS500+리뷰" },
      { label: "데카트론 러닝화 비교", url: "https://www.youtube.com/results?search_query=decathlon+kiprun+comparison" },
    ],
  },
  {
    id: "asics-jolt-4",
    brand: "Asics",
    model: "Jolt 4",
    imageUrl: "https://cdn.runrepeat.com/storage/gallery/product_primary/39800/asics-jolt-4-primary-21182975-main.jpg",
    colorways: ["블랙/화이트", "네이비"],
    widthOptions: ["D", "2E"],
    heelDropMm: 10,
    stackHeightMm: 24,
    weightGramsM9: 285,
    priceUsd: 65,
    priceKrw: 79000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "아식스 공식몰 — 졸트 4", url: "https://www.asics.co.kr/goods/search?search_text=Jolt", isOfficial: true },
      { label: "무신사 — Asics", url: "https://www.musinsa.com/brand/asics", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Asics%20Jolt%204", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Asics%20Jolt%204", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/asics-jolt-4",
    cushioning: 2,
    stability: "neutral",
    footTypes: ["neutral"],
    weightRangeKg: [50, 85],
    heightRangeCm: [150, 185],
    primaryBodyTypes: ["small_mid", "mid_mid"],
    uses: ["daily"],
    blurb: "약 8만원 최저가대 — 2E 와이드 있어 넓은 발 입문자 걷기·조깅 입문용.",
    scienceBasis: "기본 EVA 쿠션 + 2E 와이드 옵션 — 넓은 발(한국인 평균) 입문 러너의 가벼운 조깅에 무난.",
    forefootFit: "wide",
    instepVolume: "standard",
    youtubeReviews: [
      { label: "Jolt 4 리뷰", url: "https://www.youtube.com/results?search_query=asics+jolt+4+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=아식스+졸트+4+리뷰" },
      { label: "입문 러닝화 비교", url: "https://www.youtube.com/results?search_query=asics+jolt+vs+contend" },
    ],
  },
  {
    id: "nike-revolution-7",
    brand: "Nike",
    model: "Revolution 7",
    imageUrl: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/revolution-7-road-running-shoes-sWMq63.png",
    colorways: ["블랙/화이트", "그레이"],
    widthOptions: ["D"],
    heelDropMm: 9,
    stackHeightMm: 23,
    weightGramsM9: 260,
    priceUsd: 70,
    priceKrw: 79000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "나이키 공식몰 — 레볼루션 7", url: "https://www.nike.com/kr/w?q=레볼루션+7", isOfficial: true },
      { label: "무신사 — Nike", url: "https://www.musinsa.com/brand/nike", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=Nike%20Revolution%207", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=Nike%20Revolution%207", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/nike-revolution-7",
    cushioning: 2,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 80],
    heightRangeCm: [150, 182],
    primaryBodyTypes: ["small_mid", "mid_light", "mid_mid"],
    uses: ["daily"],
    blurb: "약 8만원 — 나이키 최저가대 데일리. 가벼운 조깅·걷기 입문용(앞볼은 좁은 편).",
    scienceBasis: "기본 폼 쿠션 — 가벼운 조깅·일상 입문에 적합. 앞볼이 좁아 넓은 발이면 다른 모델 권장.",
    forefootFit: "narrow",
    instepVolume: "low",
    youtubeReviews: [
      { label: "Revolution 7 리뷰", url: "https://www.youtube.com/results?search_query=nike+revolution+7+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=나이키+레볼루션+7+리뷰" },
      { label: "가성비 입문화 비교", url: "https://www.youtube.com/results?search_query=nike+revolution+7+vs+downshifter" },
    ],
  },
  {
    id: "nb-520-v9",
    brand: "New Balance",
    model: "520 v9",
    imageUrl: "https://storage.googleapis.com/tradeinn-images/web/products_image/14150/fotos/141501426.webp",
    colorways: ["블랙", "그레이/실버"],
    widthOptions: ["D", "2E"],
    heelDropMm: 8,
    stackHeightMm: 26,
    weightGramsM9: 255,
    priceUsd: 75,
    priceKrw: 89000,
    krAvailability: "kr_official",
    buyLinks: [
      { label: "뉴발란스 공식몰 — 520", url: "https://www.newbalance.co.kr/ko/search?q=520", isOfficial: true },
      { label: "무신사 — New Balance", url: "https://www.musinsa.com/brand/newbalance", isOfficial: false },
      { label: "쿠팡 검색", url: "https://www.coupang.com/np/search?q=New%20Balance%20520%20v9", isOfficial: false },
      { label: "다나와 최저가", url: "https://search.danawa.com/dsearch.php?query=New%20Balance%20520%20v9", isOfficial: false },
    ],
    gender: "male",
    sourceUrl: "https://runrepeat.com/new-balance-520-v9",
    cushioning: 2,
    stability: "neutral",
    footTypes: ["neutral", "high_arch"],
    weightRangeKg: [45, 82],
    heightRangeCm: [150, 185],
    primaryBodyTypes: ["small_mid", "mid_light", "mid_mid"],
    uses: ["daily"],
    blurb: "약 9만원 — 2E 와이드 있는 가성비 데일리. 넓은 발 입문자 일상·조깅용.",
    scienceBasis: "Fresh Foam 계열 기본 쿠션 + 2E 와이드 — 넓은 발 입문 러너에게 부담 없는 일상화.",
    forefootFit: "wide",
    instepVolume: "standard",
    youtubeReviews: [
      { label: "520 v9 리뷰", url: "https://www.youtube.com/results?search_query=new+balance+520+review" },
      { label: "한국어 리뷰", url: "https://www.youtube.com/results?search_query=뉴발란스+520+리뷰" },
      { label: "가성비 입문화 비교", url: "https://www.youtube.com/results?search_query=new+balance+520+vs+fresh+foam" },
    ],
  },
];
